site_name: Networking Notes
site_url: https://edm0nddantes.github.io/Networking-Notes/
theme:
  name: material
  font:
    code: Red Hat Mono
  logo: assets/Router-Firewall.svg
  favicon: assets/Router-Firewall.svg
  features:
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    scheme: slate
    primary: light blue
nav: 
  - BGP: bgp.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight

extra:
  social:
    - icon: simple/github
      link: https://github.com/Edm0ndDantes